name: "Package Skills"
description: "Creates distributable .zip files from skill directories for Claude.ai and compatible clients"
branding:
  icon: "package"
  color: "purple"

inputs:
  skill-paths:
    description: "Newline-separated list of skill directory paths (e.g., from paths-filter)"
    required: false
  skills-dir:
    description: "Root directory to scan for skills (used if skill-paths not provided)"
    required: false
    default: "skills"
  output-dir:
    description: "Directory for output .zip files and manifest"
    required: false
    default: "dist"
  validate-only:
    description: "Only validate skills, do not package"
    required: false
    default: "false"
  create-release:
    description: "Create GitHub releases for packaged skills"
    required: false
    default: "false"
  version:
    description: "Explicit version override (skips plugin.json lookup)"
    required: false
  release-prefix:
    description: "Prefix for release tags (e.g., 'my-plugin-')"
    required: false
  draft:
    description: "Create releases as drafts"
    required: false
    default: "false"
  force-all:
    description: "Package all skills regardless of changes"
    required: false
    default: "false"
  since:
    description: "Git ref to compare against (tag, branch, or SHA). Auto-detected if not provided."
    required: false

outputs:
  packages:
    description: "JSON array of packaged skills with metadata"
    value: ${{ steps.package.outputs.packages }}
  manifest:
    description: "Path to generated manifest.json"
    value: ${{ steps.package.outputs.manifest }}
  valid:
    description: "Whether all skills passed validation"
    value: ${{ steps.package.outputs.valid }}
  groups:
    description: "JSON array of skill groups (grouped by plugin)"
    value: ${{ steps.package.outputs.groups }}
  releases:
    description: "JSON array of created releases (when create-release is true)"
    value: ${{ steps.package.outputs.releases }}

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
    - id: package
      shell: bash
      run: bun run ${{ github.action_path }}/src/package.ts
      env:
        INPUT_SKILL_PATHS: ${{ inputs.skill-paths }}
        INPUT_SKILLS_DIR: ${{ inputs.skills-dir }}
        INPUT_OUTPUT_DIR: ${{ inputs.output-dir }}
        INPUT_VALIDATE_ONLY: ${{ inputs.validate-only }}
        INPUT_CREATE_RELEASE: ${{ inputs.create-release }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_RELEASE_PREFIX: ${{ inputs.release-prefix }}
        INPUT_DRAFT: ${{ inputs.draft }}
        INPUT_FORCE_ALL: ${{ inputs.force-all }}
        INPUT_SINCE: ${{ inputs.since }}
